version: "3"
services:
  gateway:
    networks:
      director:
        ipv4_address: 172.18.45.4
  director:
    container_name: director
    build: ./mirrorbits/
    depends_on:
      - director-redis
      - rsync
      - updater
    volumes:
      - ./data/geoipdb:/var/lib/GeoIP
      - ./mirrorbits/mirrors.sh:/mirrors.sh
      - ./data/repository:/var/www/repository
      - ./data/logs/mirrorbits:/var/log/mirrorbits
    restart: always
    expose:
      - "8080"
    networks:
      main:
        ipv4_address: 172.18.10.4
      director:
        ipv4_address: 172.18.45.2
  director-redis:
    container_name: redis
    image: redis
    volumes:
      - ./data/redis:/data
    command: /usr/local/bin/redis-server --appendonly yes
    networks:
      director:
        ipv4_address: 172.18.45.3

networks:
  director:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.45.0/29