version: "3"
services:
  gateway:
    container_name: gateway
    build: ./gateway/
    volumes:
      - /root/certs:/root/certs
      - ./data/website/html:/var/www/html/
      - ./data/website/docs:/var/www/docs
      - ./data/website/static:/var/www/static
      - ./data/repository/:/var/www/repository/
      - ./speedtest/:/var/www/speedtest/
      - ./speedtest/:/var/www/repository/speedtest/
      - ./gateway/realip.conf:/etc/nginx/snippets/realip.conf
      - ./gateway/snakeoil.conf:/etc/nginx/snippets/snakeoil.conf
      - ./gateway/cache-buffer.conf:/etc/nginx/snippets/cache-buffer.conf
      - ./gateway/cache-aggressive.conf:/etc/nginx/snippets/cache-aggressive.conf
      - ./gateway/sites-available:/etc/nginx/sites-available
      - ./gateway/sites-available/default:/etc/nginx/sites-enabled/default
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/php-fpm.conf:/etc/nginx/snippets/php-fpm.conf
      - ./data/logs/gateway:/var/log/nginx
    restart: always
    depends_on:
      - php-repo
     # - ipfs
    ports:
      - "80:80"
      - "443:443"
    networks:
      main:
      ipfs:
        ipv4_address: 172.18.44.3
  
  php-repo:
    container_name: php-repo
    image: php:7.3-fpm-buster
    volumes:
      - ./data/repository/speedtest:/var/www/repository/speedtest
      - ./speedtest/:/var/www/speedtest/
    expose:
      - "9000"
    restart: always
    networks:
      - main
      
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs
    privileged: true
    ports:
      - "4001:4001" # ipfs swarm
    #  - "5001:5001" # ipfs api
      - "8080:8080" # ipfs gateway
    expose:
      - 4001
      - 5001
      - 8080
    volumes:
      - ./data/ipfs:/data/ipfs
    restart: always
    networks:
      ipfs:
        ipv4_address: 172.18.44.2
  
  ipfs-updater:
    container_name: ipfs-updater
    build: ./updater/
    depends_on:
      - ipfs
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./data/website/html:/var/www/html/
      - ./data/website/docs:/var/www/docs
      - ./data/website/static:/var/www/static
      - ./updater/webupdate.sh:/webupdate.sh
    restart: always
    networks:
      ipfs:
        ipv4_address: 172.18.44.4
    command: /bin/bash /webupdate.sh

networks:
  main:
    driver: bridge
  ipfs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.44.0/29
