version: "3"
services:
  dnsdist:
    container_name: dnsdist
    build: ./geodns/dnsdist/
    restart: always
    depends_on:
      - pdns
      - recursor
      - gateway
    ports:
      - "53:53/udp"
      - "53:53"
    expose:
      - "53"
    volumes:
      - ./geodns/dnsdist.conf:/etc/dnsdist/dnsdist.conf
    networks:
      dnsnet:
        ipv4_address: 172.18.12.2
  pdns:
    container_name: pdns
    build: ./geodns/pdns/
    restart: always
    depends_on:
      - geoipupdate
    expose:
      - "8053"
    volumes:
      - ./data/geoipdb:/var/lib/GeoIP
      - ./geodns/pdns.conf:/etc/powerdns/pdns.conf
      - ./geodns/pdns.service:/lib/systemd/system/pdns.service
      - ./geodns/geoip.conf:/etc/powerdns/pdns.d/geoip.conf
      - ./geodns/zones.yml:/etc/powerdns/zones.yml
    networks:
      dnsnet:
        ipv4_address: 172.18.12.3
  recursor:
    container_name: recursor
    build: ./geodns/recursor/
    restart: always
    expose:
      - "8153"
    volumes:
      - ./geodns/recursor.conf:/etc/powerdns/recursor.conf
      - ./geodns/pdns-recursor.service:/lib/systemd/system/pdns-recursor.service
      - ./geodns/root.hints:/etc/powerdns/root.hints
    networks:
      dnsnet:
        ipv4_address: 172.18.12.4
  geoipupdate:
    container_name: geoipupdate
    build: ./geodns/geoipupdate/
    volumes:
      - ./data/geoipdb:/var/lib/GeoIP
      - /etc/GeoIP.conf:/etc/GeoIP.conf
    restart: always



networks:
  dnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.12.0/24
