version: "3"
services:
  gateway:
    volumes:
      - ./gateway/sites-available/repo:/etc/nginx/sites-enabled/repo
  rsync:
    container_name: rsyncd
    build: ./rsync/
    volumes:
      - ./data/repository/:/var/www/repository/
      - ./rsync/rsyncd.conf:/etc/rsyncd.conf
    restart: always
    ports:
     - "873:873"
    networks:
      - main
  updater:
    container_name: updater
    build: ./updater/
    volumes:
      - ./data/repository/:/var/www/repository
    restart: always