version: "3"
services:
  gateway:
    container_name: gateway
    build: ./gateway/
    volumes:
      - ./data/gateway/html:/var/www/html
      - ./data/certs:/root/certs
      - ./data/logs/gateway:/var/log/nginx
      - ./gateway/snakeoil.conf:/etc/nginx/snippets/snakeoil.conf
      - ./gateway/default:/etc/nginx/sites-enabled/default
      - ./gateway/realip.conf:/etc/nginx/snippets/realip.conf
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - website
      - wekan
      - tracker
    ports:
      - "80:80"
      - "443:443"
    networks:
      internal:
        ipv4_address: 172.18.42.2
      wekan:

  tracker:
    container_name: tracker
    build: ./tracker/
    expose:
      - "80"
    ports:
      - "6880:6880"
      - "6969:6969"
    volumes:
      - ./tracker/config.conf:/config.conf
    restart: always
    networks:
      internal:
        ipv4_address: 172.18.42.5
      phpnet:
        ipv4_address: 172.18.43.5

  website:
    container_name: website
    build: ./website/
    depends_on:
      - php
    expose:
      - "80"
      - "443"
    volumes:
      - ./data/website:/var/www
      - ./data/logs/website:/var/log/nginx
      - ./website/default:/etc/nginx/sites-enabled/default
      - ./website/php-fpm.conf:/etc/nginx/snippets/php-fpm.conf
    restart: always
    networks:
      internal:
        ipv4_address: 172.18.42.3
      phpnet:
        ipv4_address: 172.18.43.3

  php:
    container_name: php
    build: ./php/
    volumes:
      - ./data/website:/var/www
    expose:
      - "9000"
    restart: always
    networks:
      phpnet:
        ipv4_address: 172.18.43.2

  manager:
    container_name: manager
    build: ./manager/
    volumes:
      - ./data/:/data
      - ./websites.txt:/data/websites.txt
    restart: always
  
  wekan-db:
    container_name: wekan-db
    image: mongo:4.0
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan
    expose:
      - 27017
    volumes:
      - ./data/wekan/db:/data/db
      - ./data/wekan/dump:/dump
  wekan:
    container_name: wekan
    image: wekanteam/wekan:meteor-1.8
    depends_on:
      - wekan-db
    restart: always
    networks:
      - wekan
    expose:
      - 8080
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=https://board.parrotlinux.org
      - MAIL_FROM='Parrot Board <noreply.board@parrotsec.org>'
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true

  cryptpad:
    container_name: cryptpad
    image: cryptpad/cryptpad
    restart: always
    expose:
      - "3000"
      - "3001"
    volumes:
      - ./data/cryptpad/files:/cryptpad/datastore:rw
      - ./data/cryptpad/customize:/cryptpad/customize:rw
      - ./data/cryptpad/pins:/cryptpad/pins:rw
      - ./data/cryptpad/blob:/cryptpad/blob:rw
      - ./data/cryptpad/blobstage:/cryptpad/blobstage:rw
      - ./data/cryptpad/tasks:/cryptpad/tasks:rw
      - ./data/cryptpad/block:/cryptpad/block:rw
      - ./data/cryptpad/config:/cryptpad/cfg:rw
      - ./data/cryptpad/data:/cryptpad/data:rw
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.42.0/24
  archive:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.44.0/24
  phpnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.43.0/24
  wekan:
    driver: bridge
