version: "3"
services:
  gateway:
    volumes:
      - ./gateway/sites-available/cryptpad-master:/etc/nginx/sites-enabled/cryptpad

  cryptpad:
    container_name: cryptpad
    image: cryptpad/cryptpad
    restart: always
    depends_on:
      - gateway
    expose:
      - "3000"
      - "3001"
    volumes:
      - ./data/cryptpad/files:/cryptpad/datastore:rw
      - ./data/cryptpad/customize:/cryptpad/customize:rw
      - ./data/cryptpad/pins:/cryptpad/pins:rw
      - ./data/cryptpad/blob:/cryptpad/blob:rw
      - ./data/cryptpad/blobstage:/cryptpad/blobstage:rw
      - ./data/cryptpad/tasks:/cryptpad/tasks:rw
      - ./data/cryptpad/block:/cryptpad/block:rw
      - ./data/cryptpad/config:/cryptpad/cfg:rw
      - ./data/cryptpad/data:/cryptpad/data:rw
    networks:
      - main