version: "3"
services:
  gateway:
    container_name: gateway
    build: ./gateway/
    volumes:
      - ./data/gateway/cache:/srv/
      - ./data/gateway/html:/var/www/html
      - ./data/certs:/root/certs
      - ./data/logs/gateway:/var/log/nginx
      - ./gateway/snakeoil.conf:/etc/nginx/snippets/snakeoil.conf
      - ./gateway/sites-enabled/:/etc/nginx/sites-enabled/
      - ./gateway/realip.conf:/etc/nginx/snippets/realip.conf
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      internal:
        ipv4_address: 172.18.10.2

  dnsdist:
    container_name: dnsdist
    build: ./geodns/dnsdist/
    restart: always
    depends_on:
      - pdns
      - recursor
      - gateway
    ports:
      - "53:53/udp"
      - "53:53"
    expose:
      - "53"
    volumes:
      - ./geodns/dnsdist.conf:/etc/dnsdist/dnsdist.conf
    networks:
      dnsnet:
        ipv4_address: 172.18.12.2
  pdns:
    container_name: pdns
    build: ./geodns/pdns/
    restart: always
    expose:
      - "8053"
    volumes:
      - ./geodns/pdns.conf:/etc/powerdns/pdns.conf
      - ./geodns/pdns.service:/lib/systemd/system/pdns.service
      - ./geodns/geoip.conf:/etc/powerdns/pdns.d/geoip.conf
      - ./geodns/geo.yml:/etc/powerdns/geo.yml
    networks:
      dnsnet:
        ipv4_address: 172.18.12.3
  recursor:
    container_name: recursor
    build: ./geodns/recursor/
    restart: always
    expose:
      - "8153"
    volumes:
      - ./geodns/recursor.conf:/etc/powerdns/recursor.conf
      - ./geodns/pdns-recursor.service:/lib/systemd/system/pdns-recursor.service
      - ./geodns/root.hints:/etc/powerdns/root.hints
    networks:
      dnsnet:
        ipv4_address: 172.18.12.4

  firewall:
    container_name: firewall
    build: ./firewall/
    restart: always
    volumes:
      - ./firewall/jail/:/etc/fail2ban/jail.d/
      - ./firewall/filter/:/etc/fail2ban/filter.d/
      - ./data/logs/:/logs/
    network_mode: "host"
    privileged: true
    cap-add:
      - NET_ADMIN
      - NET_RAW



networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.10.0/24
  dnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.12.0/24

